version: '3'
services:
    mongoPep:
        image: mongo:3.2
        restart: always
        ports:
            - 27117:27017
        networks:
            main:
        volumes:
            - ./mongo-data:/data/db
    pep:
        image: angelocapossele/pep-proxy-plus:latest
        restart: always
        links:
            - mongoPep
        volumes:
            - ./config.js:/opt/fiware-pep-proxy/config.js
        ports:
            - 7000:7000
        networks:
            main:
                aliases:
                    - pep.docker

networks:
    main:
        external: true
